name: Node CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Create Artifact
        run: zip -r app-artifact.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: app-artifact.zip